### ISSUE TITLE
stackoverflow completing import

### ISSUE THREAD

**Issue by expez** [alexander-yakushev/compliment#27]
```
ERROR: Unhandled REPL handler exception processing message {:op complete, :session 5eefc359-1330-474e-bd86-9df453b135af, :ns refactor-nrepl.rename-file-or-dir, :symbol jav, :context :same, :id 503}

java.lang.StackOverflowError

	at clojure.lang.LazySeq.sval(LazySeq.java:42)

	at clojure.lang.LazySeq.seq(LazySeq.java:60)

	at clojure.lang.RT.seq(RT.java:484)

	at clojure.core$seq.invoke(core.clj:133)

	at clojure.core$concat$fn__3923.invoke(core.clj:678)

	at clojure.lang.LazySeq.sval(LazySeq.java:42)

	at clojure.lang.LazySeq.seq(LazySeq.java:60)

	at clojure.lang.RT.seq(RT.java:484)

	at clojure.core$seq.invoke(core.clj:133)

	at clojure.core$concat$fn__3923.invoke(core.clj:678)

```

Reminded me of [this blog post](http://stuartsierra.com/2015/04/26/clojure-donts-concat)

Hopefully this is enough to go on, the stacktrace is entirely without reference to any of your code :/

**Comment by alexander-yakushev** [comment]
Can you provide the scenario please?

**Comment by expez** [comment]
I was trying to import `java.regex.Pattern` and only got as far as `jav|` and got the stackoverflow.  This caused emacs to freeze until the request timed out.

**Comment by alexander-yakushev** [comment]
I can't reproduce, but I know where a problem can be. I pushed `0.2.3-SNAPSHOT` with a fix to one shady `concat` usage, please try.

**Comment by expez** [comment]
Haven't seen this one again.  Thanks!
